export enum ControlKey {

    GRP_IDENTITY = 'identity',
    GRP_APPLICANT = 'applicant',
    GRP_CONJOINT = 'conjoint',
    GRP_CHILDREN_INFO = 'childrenInfo',
    GRP_ADDRESS_INFO = 'addressInfo',
    GRP_BANK_INFO = 'bankInfo',
    GRP_CONTACT_INFO = 'contactInfo',
    GRP_GENERAL_INFO = 'generalInfo',
    GRP_CHILD_LINK = 'childLink',
    GRP_PRO_SITUATION = 'proSituation',
    GRP_INCOME = 'income',
    GRP_SOCIAL_SECURITY = 'socialSecurity',
    GRP_FAMILY_SITUATION = 'familySituation',

    AUTH_EMAIL = 'email',
    AUTH_PASSWORD = 'password',

    BANK_NAME = 'bankName',
    BANK_IBAN = 'iban',
    BANK_BIC = 'bic',
    BANK_CODE = 'bankCode',
    BANK_CODE_GUICHET = 'codeGuichet',
    BANK_ACCOUNT_NBR = 'accountNbr',
    BANK_RIB_KEY = 'ribKey',
    BANK_ADDRESS = 'bankAddress',

    FIRSTNAME = 'firstName',
    MARRIEDNAME = 'marriedName',
    BIRTHNAME = 'birthName',
    DATE_OF_BIRTH = 'dateOfBirth',
    PLACE_OF_BIRTH = 'placeOfBirth',
    NATIONALITY = 'nationality',
    PRCT_HANDI = 'prctHandi',
    MARITAL_STATUS = 'maritalStatus',
    MARITAL_SITUATION_DATE = 'maritalSituationDate',
    CHILD_LINK = 'link',
    CHILD_LINK_PRECISION = 'linkPrecision',
    PRO_SITUATION = 'proSituation',
    PRO_SITUATION_DATE = 'proSituationDate',
    EMPLOYER_NAME = 'employerName',
    JOB_TITLE = 'jobTitle',
    MONTHLY_PAY = 'monthlyPay',
    PENSION = 'pension',
    INCOME = 'income',
    LIBERAL_INCOME = 'liberalIncome',
    OTHER_INCOME = 'otherIncome',
    SOCIAL_SECURITY_ORGA = 'organisms',
    ADDRESS_AT = 'at',
    ADDRESS_APPT_NBR = 'apptNbr',
    ADDRESS_STAIR = 'stair',
    ADDRESS_BAT_INFO = 'batInfo',
    ADDRESS_STREET = 'street',
    ADDRESS_DISTRICT = 'district',
    ADDRESS_BP = 'bp',
    ADDRESS_POSTAL_CODE = 'postalCode',
    ADDRESS_CITY = 'city',
    CONTACT_PHONE_HOME = 'phoneHome',
    CONTACT_PHONE_WORK = 'phoneWork',
    CONTACT_PHONE_CELL = 'phoneCell',
    CONTACT_EMAIL = 'receptionEmail',

    NBR_CHILDREN = 'nbrChildren',
    NBR_HANDI = 'nbrHandi',
    CHILDREN = 'children',

    FAMILYNAME = 'familyName',
    GENDER = 'gender',
    LAST_YEAR_SCHOLARLEVEL = 'lastYearScholarLevel',
    NEXT_YEAR_SCHOLARLEVEL = 'nextYearScholarLevel',
    NEXT_YEAR_SCHOOL = 'nextYearSchool',
    UNSCHOOLED = 'unschooled',
    SCHOLAR_LEVEL = 'scholarLevel',
}
